GET http://localhost:3000/api/auth/login

###

POST http://localhost:3000/api/auth/refresh-token
Cookie:refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzYzNTFmMGE4ODZmMzU3MGZlN2RlYiIsImlhdCI6MTczNTk2MjcyMiwiZXhwIjoxNzM2NTY3NTIyfQ.74yqzSp_dwyMptl28Wf96tS0uhaVZIN5j7EzpzMpXiY


###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name":"최영tjjs",
  "email": "sunn7933@naver.com",
  "password": "dkssud!96",
  "passwordCheck": "1234qwer!"
}

###

DELETE http://localhost:3000/api/auth/6773e1476c4ee90bce65a839
Content-Type: application/json

###

GET http://localhost:3000/api/users/6773e1476c4ee90bce65a839
Content-Type: application/json

###

GET http://localhost:3000/api/users/
Content-Type: application/json

### Put Affiliation from Groom Side
PATCH http://localhost:3000/api/users/setting
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzYzNTFmMGE4ODZmMzU3MGZlN2RlYiIsImlhdCI6MTczNTk3MjkzOCwiZXhwIjoxNzM1OTc2NTM4fQ.pmCz7tF-9WhSLMMrNgJP663s8_3qcUFvdWUmRkAVGoA;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzYzNTFmMGE4ODZmMzU3MGZlN2RlYiIsImlhdCI6MTczNTk3MjkzOCwiZXhwIjoxNzM2NTc3NzM4fQ.mwZ24AJrOLpVEsIe_Gmo9mVGX36CLUIcIe011iIzY4U

{
  "side": "brideSide",
  "affiliation": "가족",
  "action": "add"
}

### Put Affiliation from Groom Side
GET http://localhost:3000/api/users/setting
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzYzNTFmMGE4ODZmMzU3MGZlN2RlYiIsImlhdCI6MTczNTk3Nzg4MiwiZXhwIjoxNzM1OTgxNDgyfQ.hX0wAThms3MxWLube62zCz19gLVTfLA2gQWZ-ajbGis;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzYzNTFmMGE4ODZmMzU3MGZlN2RlYiIsImlhdCI6MTczNTk3MjkzOCwiZXhwIjoxNzM2NTc3NzM4fQ.mwZ24AJrOLpVEsIe_Gmo9mVGX36CLUIcIe011iIzY4U
