export const brideGuest = [
  {
    id: 1,
    userId: 1,
    orderNumber: 1,
    side: '신부측',
    guestName: '이민준',
    group: '가족',
    giftAmount: 100000,
    ticketCount: 2,
    note: '',
  },
  {
    id: 2,
    userId: 1,
    orderNumber: 2,
    side: '신부측',
    guestName: '김하영',
    group: '직장',
    giftAmount: 50000,
    ticketCount: '',
    note: '',
  },
  {
    id: 3,
    userId: 1,
    orderNumber: 3,
    side: '신부측',
    guestName: '박지우',
    group: '대학교',
    giftAmount: 70000,
    ticketCount: '',
    note: '친구',
  },
  {
    id: 4,
    userId: 1,
    orderNumber: 4,
    side: '신부측',
    guestName: '정수민',
    group: '초등학교',
    giftAmount: 30000,
    ticketCount: '',
    note: '',
  },
  {
    id: 5,
    userId: 1,
    orderNumber: 5,
    side: '신부측',
    guestName: '최윤서',
    group: '중/고등학교',
    giftAmount: '',
    ticketCount: 1,
    note: '은사님',
  },
  {
    id: 6,
    userId: 1,
    orderNumber: 6,
    side: '신부측',
    guestName: '한도현',
    group: '직장',
    giftAmount: 80000,
    ticketCount: '',
    note: '',
  },
  {
    id: 7,
    userId: 1,
    orderNumber: 7,
    side: '신부측',
    guestName: '장예은',
    group: '가족',
    giftAmount: 150000,
    ticketCount: 4,
    note: '',
  },
  {
    id: 8,
    userId: 1,
    orderNumber: 8,
    side: '신부측',
    guestName: '윤지환',
    group: '대학교',
    giftAmount: 40000,
    ticketCount: '',
    note: '동아리 선배',
  },
  {
    id: 9,
    userId: 1,
    orderNumber: 9,
    side: '신부측',
    guestName: '오현지',
    group: '기타',
    giftAmount: 60000,
    ticketCount: '',
    note: '이웃',
  },
  {
    id: 10,
    userId: 1,
    orderNumber: 10,
    side: '신부측',
    guestName: '이서준',
    group: '중/고등학교',
    giftAmount: 55000,
    ticketCount: 2,
    note: '',
  },
  {
    id: 21,
    userId: 1,
    orderNumber: 11,
    side: '신부측',
    guestName: '이민준',
    group: '가족',
    giftAmount: 100000,
    ticketCount: 2,
    note: '',
  },
  {
    id: 22,
    userId: 1,
    orderNumber: 12,
    side: '신부측',
    guestName: '김하영',
    group: '직장',
    giftAmount: 50000,
    ticketCount: '',
    note: '',
  },
  {
    id: 23,
    userId: 1,
    orderNumber: 13,
    side: '신부측',
    guestName: '박지우',
    group: '대학교',
    giftAmount: 70000,
    ticketCount: '',
    note: '친구',
  },
  {
    id: 24,
    userId: 1,
    orderNumber: 14,
    side: '신부측',
    guestName: '정수민',
    group: '초등학교',
    giftAmount: 30000,
    ticketCount: '',
    note: '',
  },
  {
    id: 25,
    userId: 1,
    orderNumber: 15,
    side: '신부측',
    guestName: '최윤서',
    group: '중/고등학교',
    giftAmount: '',
    ticketCount: 1,
    note: '은사님',
  },
  {
    id: 26,
    userId: 1,
    orderNumber: 16,
    side: '신부측',
    guestName: '한도현',
    group: '직장',
    giftAmount: 80000,
    ticketCount: '',
    note: '',
  },
  {
    id: 27,
    userId: 1,
    orderNumber: 17,
    side: '신부측',
    guestName: '장예은',
    group: '가족',
    giftAmount: 150000,
    ticketCount: 4,
    note: '',
  },
  {
    id: 28,
    userId: 1,
    orderNumber: 18,
    side: '신부측',
    guestName: '윤지환',
    group: '대학교',
    giftAmount: 40000,
    ticketCount: '',
    note: '동아리 선배',
  },
  {
    id: 29,
    userId: 1,
    orderNumber: 19,
    side: '신부측',
    guestName: '오현지',
    group: '기타',
    giftAmount: 60000,
    ticketCount: '',
    note: '이웃',
  },
  {
    id: 30,
    userId: 1,
    orderNumber: 20,
    side: '신부측',
    guestName: '이서준',
    group: '중/고등학교',
    giftAmount: 55000,
    ticketCount: 2,
    note: '',
  },
];

export const broomGuest = [
  {
    id: 11,
    userId: 1,
    orderNumber: 1,
    side: '신랑측',
    guestName: '이윤아',
    group: '가족',
    giftAmount: 90000,
    ticketCount: 3,
    note: '',
  },
  {
    id: 12,
    userId: 1,
    orderNumber: 2,
    side: '신랑측',
    guestName: '김동현',
    group: '직장',
    giftAmount: 100000,
    ticketCount: '',
    note: '',
  },
  {
    id: 13,
    userId: 1,
    orderNumber: 3,
    side: '신랑측',
    guestName: '박서영',
    group: '대학교',
    giftAmount: 70000,
    ticketCount: '',
    note: '',
  },
  {
    id: 14,
    userId: 1,
    orderNumber: 4,
    side: '신랑측',
    guestName: '정민호',
    group: '초등학교',
    giftAmount: 30000,
    ticketCount: '',
    note: '',
  },
  {
    id: 15,
    userId: 1,
    orderNumber: 5,
    side: '신랑측',
    guestName: '최수현',
    group: '중/고등학교',
    giftAmount: '',
    ticketCount: 1,
    note: '',
  },
  {
    id: 16,
    userId: 1,
    orderNumber: 6,
    side: '신랑측',
    guestName: '한지훈',
    group: '직장',
    giftAmount: 80000,
    ticketCount: '',
    note: '',
  },
  {
    id: 17,
    userId: 1,
    orderNumber: 7,
    side: '신랑측',
    guestName: '장하은',
    group: '가족',
    giftAmount: 150000,
    ticketCount: 4,
    note: '',
  },
  {
    id: 18,
    userId: 1,
    orderNumber: 8,
    side: '신랑측',
    guestName: '윤도윤',
    group: '대학교',
    giftAmount: 40000,
    ticketCount: '',
    note: '동아리 후배',
  },
  {
    id: 19,
    userId: 1,
    orderNumber: 9,
    side: '신랑측',
    guestName: '오지민',
    group: '기타',
    giftAmount: 60000,
    ticketCount: '',
    note: '이웃',
  },
  {
    id: 20,
    userId: 1,
    orderNumber: 10,
    side: '신랑측',
    guestName: '이승민',
    group: '중/고등학교',
    giftAmount: 55000,
    ticketCount: 2,
    note: '친구',
  },
];
